
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NTIxMDc2MTl9.ezcfM0VkJqMzSbPR3eb0fJh9mmozb38MVawxNmFmMQY
###exercise Index
GET http://localhost:3000/exercises/

###exercise show
GET http://localhost:3000/exercises/4

###exercise create
POST http://localhost:3000/exercises/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "push ups",
  "instructions": "",
  "frequency": "2 x 10,3x/wk.",
  "image": ""
}

###exercise update
PATCH http://localhost:3000/exercises/
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Billy",
  "email": "billy@example.com",
  "password": "password",
  "password_confirmation": "password",
  "admin": true
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "steve@example.com",
  "password": "password"
}