
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NTI3MTI5OTd9.v8nbZ9HWd2RTQzA_V2vOoTZSJU0X_9Ldwm8jCdXDY9I
###exercise Index
GET http://localhost:3000/exercises/

###exercise show
GET http://localhost:3000/exercises/4

###exercise create
POST http://localhost:3000/exercises/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Test",
  "instructions": "test",
  "frequency": "2 x 10,3x/wk.",
  "image": ""
}

###exercise update
PATCH http://localhost:3000/exercises/
Authorization: Bearer {{jwt}}
Content-Type: application/json

###user Index
GET http://localhost:3000/users/

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Winter Sun",
  "email": "wintersun@example.com",
  "password": "password",
  "password_confirmation": "password",
  "admin": true,
  "phone": "",
  "age": 32,
  "profile_pic": "",
  "injury_diagnosis": "low back pain"
}

### Users Show
GET http://localhost:3000/users/8

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "steve@example.com",
  "password": "password"
}

###program index
GET http://localhost:3000/programs
Authorization: Bearer {{jwt}}

###program create
POST http://localhost:3000/programs/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": 5,
  "user_rating": "easy",
  "title": "Shoulder"
}

###exercise_program create
POST http://localhost:3000/exercise_programs/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "program_id": 4,
  "exercise_id": 2
}

###exercise_program index
GET http://localhost:3000/exercise_programs
Authorization: Bearer {{jwt}}

###twilio create
POST http://localhost:3000/textremind

